export const FETCH_SHOES_REQUEST = 'FETCH_SHOES_REQUEST';
export const FETCH_SHOES_FAILURE = 'FETCH_SHOES_FAILURE';
export const FETCH_SHOES_SUCCESS = 'FETCH_SHOES_SUCCESS';

export const BESTSELLERS_REQUEST = 'BESTSELLERS_REQUEST';
export const BESTSELLERS_FAILURE = 'BESTSELLERS_FAILURE';
export const BESTSELLERS_SUCCESS = 'BESTSELLERS_SUCCESS';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';

export const FETCH_SHOES_DETAILS_REQUEST = 'FETCH_SHOES_DETAILS_REQUEST';
export const FETCH_SHOES_DETAILS_FAILURE = 'FETCH_SHOES_DETAILS_FAILURE';
export const FETCH_SHOES_DETAILS_SUCCESS = 'FETCH_SHOES_DETAILS_SUCCESS';

export const SHOES_QUERY_APPLY_CATEGORY = 'SHOES_QUERY_APPLY_CATEGORY';
export const SHOES_QUERY_APPLY_SEARCH_FILTER = 'SHOES_QUERY_APPLY_SEARCH_FILTER';
export const SHOES_QUERY_LOAD_NEXT_PAGE = 'SHOES_QUERY_LOAD_NEXT_PAGE';

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';